M48
; DRILL file {KiCad 7.0.1} date Mon Mar 20 20:32:50 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-20T20:32:50+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.305
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X-6.0Y-3.5
X-5.0Y-3.5
X-4.0Y-3.5
X-3.0Y-3.5
X-2.0Y-3.5
X3.5Y-3.5
X4.5Y-3.5
X5.5Y-3.5
X6.5Y-3.5
T2
X-8.0Y0.0
X-6.0Y0.0
X-4.0Y0.0
X-2.0Y0.0
X0.0Y0.0
X2.0Y0.0
X4.0Y0.0
X6.0Y0.0
X8.0Y0.0
T0
M30
